### ISSUE TITLE
Fix Options link in README.md

### ISSUE THREAD

**Issue by bzgec** [asciidoctor/asciidoctor-vscode#405]
in `README.md` there are links to `Options` which are broken. I guess `Options` are now called `User Settings`.

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue

**Comment by Mogztter** [comment]
I think this is already fixed: https://github.com/asciidoctor/asciidoctor-vscode#user-settings
@himanshu007-creator @bzgec could you please confirm?

**Comment by himanshu007-creator** [comment]
> I think this is already fixed: https://github.com/asciidoctor/asciidoctor-vscode#user-settings
> @himanshu007-creator @bzgec could you please confirm?

no its not fixed, see line 55, 66, referrence is still made to #Options

**Comment by Mogztter** [comment]
Oh you're right, nice catch!
Yes, we need to fix these links 👍🏻
